version: '3.8'

services:
  antink-server:
    build: ./server
    container_name: antink-server
    privileged: true
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - ./it24_host:/it24_host:ro
      - antink_mount:/antink_mount
      - ./var/log:/var/log
 
    networks:
      - antink-net

  antink-logger:
    image: busybox:stable
    container_name: antink-logger
    command: sh -c "tail -F /var/log/it24.log"
    volumes:
      - ./var/log:/var/log
    networks:
      - antink-net

volumes:
  antink_mount:
  antink_logs:

networks:
  antink-net:
